version: "3.8"

services:
  backend:
    build: ./backend
    command: gunicorn market_tracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on: []

  frontend:
    working_dir: /app/frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
